version: '3.1'
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_ROOT_HOST=%
    ports:
    - 3306:3306
    volumes:
    - ./mysql/dbdata:/var/lib/mysql/
    - ./mysql/my.cnf:/etc/mysql/my.cnf
    - ./init_db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
